apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-deployment
spec:
  replicas: 2     # Number of app pods to run
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp  # Pods will get this label for selector matching
    spec:
      containers:
        - name: helloapp
          image: heisenberg1420/devops:771fdc688099f02b7898c6e84ad98b0ba41899a3
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
