apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-deployment
spec:
  replicas: 2     # Number of app pods to run
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp  # Pods will get this label for selector matching
    spec:
      containers:
        - name: helloapp
          image: heisenberg1420/devops:a0e4533e9fa46e488df35d423665d06561ad0cc0      
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
